service: feedback-service
package:
  version: 0.0.1-SNAPSHOT
  artifact: ./application/target/${self:service}-${self:package.version}-${self:provider}.jar
provider:
  name: aws
  runtime: java11
  region: us-east-2
  memorySize: 1024
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
  environment:
    APPLICATION_ENVIRONMENT: Dev
    CLOUD_REGION: US_East_2
functions:
  createFeedback:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: feedback/create
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: createFunction
  markFeedbackAsRead:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: feedback/markAsRead
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: markAsReadFunction
  getAllFeedbacks:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: feedback/getAll
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: getAllFunction

resources:
  Resources:
    feedbackTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Feedback
        AttributeDefinitions:
          - AttributeName: emailId
            AttributeType: S
          - AttributeName: commentedOn
            AttributeType: S
        KeySchema:
          - AttributeName: emailId
            KeyType: HASH
          - AttributeName: commentedOn
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1